#!/usr/bin/env python3
"""Bake assets/img/crest.png — the Groton School arms — into assets/data/crest.js.

Same storage contract as the portrait: one hex digit of auto-levelled *luminance*
per cell, a space where the ground was keyed out. Which end of that becomes heavy
ink is decided at render time, because it flips between the light and dark
grounds.

Two things differ from make-portrait.py, and both are about this being a drawn
mark rather than a photograph:

  - The ground is flat black, so there is no vignetting to defeat and no need to
    match a colour cast. Darkness plus the flood is the whole test.
  - Cells are *averaged*, not sampled. The motto ribbon's lettering and the
    wreath's leaf veins are one or two pixels wide; picking a single pixel out of
    each cell keeps or drops them at random and the ribbon comes out as noise.

The key is a flood inward from the border rather than a darkness threshold, for
the reason it is one on the portrait: the shield's black chief, the crimson
quarters and the outlines around the leaves are all as dark as the ground, and a
threshold erases them. Only ground *connected to the border* is ground.

    python3 tools/make-crest.py [path/to/crest.png]
"""
import json, sys
from collections import deque
from pathlib import Path
from PIL import Image

SRC    = Path(sys.argv[1] if len(sys.argv) > 1 else 'assets/img/crest.png')
OUT    = Path('assets/data/crest.js')
COLS   = 150     # bake grid; the field averages down from here to its own ~33
DARK   = 0.12    # a ground cell is at most this bright. The crimson sits at .20
LEVELS = 16
HEX    = '0123456789abcdef'

im = Image.open(SRC).convert('RGB')
W, H = im.size
px = im.load()
lum = [[(0.2126 * px[x, y][0] + 0.7152 * px[x, y][1] + 0.0722 * px[x, y][2]) / 255
        for x in range(W)] for y in range(H)]

# ---- key the ground: flood inward from the border over "is dark" -------------
bg = [[False] * W for _ in range(H)]
q = deque()
def seed(x, y):
    if lum[y][x] <= DARK and not bg[y][x]:
        bg[y][x] = True; q.append((x, y))
for x in range(W):
    seed(x, 0); seed(x, H - 1)
for y in range(H):
    seed(0, y); seed(W - 1, y)
if not q:
    sys.exit('no dark border found — is the ground light? use make-portrait.py')
while q:
    x, y = q.popleft()
    for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
        if 0 <= nx < W and 0 <= ny < H and not bg[ny][nx] and lum[ny][nx] <= DARK:
            bg[ny][nx] = True; q.append((nx, ny))

xs = [x for y in range(H) for x in range(W) if not bg[y][x]]
ys = [y for y in range(H) for x in range(W) if not bg[y][x]]
if not xs:
    sys.exit('nothing survived the key — raise DARK')
x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
sw, sh = x1 - x0 + 1, y1 - y0 + 1

# ---- reduce to the bake grid by averaging each block -------------------------
cols = COLS
rows = round(cols * (sh / sw))           # square cells; the renderer sets the aspect
cells = []
for j in range(rows):
    ya, yb = y0 + j * sh // rows, max(y0 + j * sh // rows + 1, y0 + (j + 1) * sh // rows)
    line = []
    for i in range(cols):
        xa, xb = x0 + i * sw // cols, max(x0 + i * sw // cols + 1, x0 + (i + 1) * sw // cols)
        tot = n = all_ = 0
        for y in range(ya, yb):
            for x in range(xa, xb):
                all_ += 1
                if not bg[y][x]:
                    tot += lum[y][x]; n += 1
        # a block that is mostly ground stays ground, so the mark keeps its edge
        line.append(tot / n if n * 2 >= all_ else None)
    cells.append(line)

vals = [v for line in cells for v in line if v is not None]
lo, hi = min(vals), max(vals)
span = max(1e-3, hi - lo)
def digit(v):
    if v is None:
        return ' '
    return HEX[min(LEVELS - 1, round(((v - lo) / span) ** 0.85 * (LEVELS - 1)))]

grid = [''.join(digit(v) for v in line) for line in cells]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    '/* Generated by tools/make-crest.py from %s — do not edit by hand.\n'
    '   One hex digit of auto-levelled luminance per cell; a space is ground.\n'
    '   Re-run the script after changing the artwork. */\n'
    'window.LCCrest = %s;\n' % (SRC.as_posix(), json.dumps(
        {'cols': cols, 'rows': rows, 'levels': LEVELS, 'grid': grid}, indent=0)),
    encoding='utf-8')
print('%s  %dx%d cells  %.1f KB' % (OUT, cols, rows, OUT.stat().st_size / 1024))
