#!/usr/bin/env python3
"""Bake assets/img/portrait.jpg into assets/data/portrait.js.

The site reads the baked grid rather than the photograph, because the live path
needs `getImageData`, and a canvas that has drawn a `file://` image is tainted —
so opening index.html straight off disk (which the README invites) would silently
produce no portrait at all. Baking also means no per-visit decode.

What is stored is *luminance*, not ink: one hex digit (0-f) per cell, a space for
the keyed-out backdrop. Which end of that becomes heavy ink is decided at render
time, because it flips between the light and dark grounds.

    python3 tools/make-portrait.py [path/to/photo.jpg]
"""
import json, math, sys
from pathlib import Path
from PIL import Image

SRC   = Path(sys.argv[1] if len(sys.argv) > 1 else 'assets/img/portrait.jpg')
OUT   = Path('assets/data/portrait.js')
COLS  = 150     # source sampling; the renderer scales from here
EDGE  = 0.68    # a backdrop cell is at least this bright...
CHROMA= 22      # ...and this close to the backdrop's own colour cast
LEVELS= 16
HEX   = '0123456789abcdef'

im = Image.open(SRC).convert('RGB')
W, H = im.size
cols = COLS
rows = round(cols * (H / W))          # square cells; the renderer sets the aspect
px = im.resize((cols, rows)).load()
lum = lambda p: (0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2]) / 255

edge = ([(x, y) for x in range(cols) for y in (0, rows - 1) if lum(px[x, y]) >= EDGE] +
        [(x, y) for y in range(rows) for x in (0, cols - 1) if lum(px[x, y]) >= EDGE])
if not edge:
    sys.exit('no bright border found — is the backdrop dark?')
ref = [sorted(px[x, y][c] for x, y in edge)[len(edge) // 2] for c in range(3)]
rRB, rGB = ref[0] - ref[2], ref[1] - ref[2]

def is_backdrop(x, y):
    p = px[x, y]
    return (lum(p) >= EDGE
            and abs((p[0] - p[2]) - rRB) <= CHROMA
            and abs((p[1] - p[2]) - rGB) <= CHROMA)

def flood(seeds, ok, seen):
    st = [s for s in seeds if s not in seen and ok(*s)]
    seen.update(st)
    got = list(st)
    while st:
        x, y = st.pop()
        for n in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= n[0] < cols and 0 <= n[1] < rows and n not in seen and ok(*n):
                seen.add(n); st.append(n); got.append(n)
    return got

bg = set()
flood(edge, is_backdrop, bg)

# drop speckle, but never "keep the largest": a bright collar keys out at this
# sampling and cuts the head off the body
MIN = max(8, round(cols * rows * 0.004))
seen = set(bg)
for x in range(cols):
    for y in range(rows):
        if (x, y) in seen:
            continue
        comp = flood([(x, y)], lambda a, b: (a, b) not in bg, seen)
        if len(comp) < MIN:
            bg.update(comp)

keep = [(x, y) for x in range(cols) for y in range(rows) if (x, y) not in bg]
if not keep:
    sys.exit('nothing survived the key — loosen EDGE/CHROMA')
xs = [p[0] for p in keep]; ys = [p[1] for p in keep]
x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
vals = {p: lum(px[p[0], p[1]]) for p in keep}
lo, hi = min(vals.values()), max(vals.values())
span = max(1e-3, hi - lo)

grid = []
for y in range(y0, y1 + 1):
    line = ''
    for x in range(x0, x1 + 1):
        if (x, y) in bg:
            line += ' '
        else:
            v = ((vals[(x, y)] - lo) / span) ** 0.85       # auto-levelled luminance
            line += HEX[min(LEVELS - 1, round(v * (LEVELS - 1)))]
    grid.append(line)

cw, ch = x1 - x0 + 1, y1 - y0 + 1
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    '/* Generated by tools/make-portrait.py from %s — do not edit by hand.\n'
    '   One hex digit of auto-levelled luminance per cell; a space is backdrop.\n'
    '   Re-run the script after changing the photograph. */\n'
    'window.LCPortrait = %s;\n' % (SRC.as_posix(), json.dumps(
        {'cols': cw, 'rows': ch, 'levels': LEVELS, 'grid': grid}, indent=0)),
    encoding='utf-8')
print('%s  %dx%d cells  %.1f KB' % (OUT, cw, ch, OUT.stat().st_size / 1024))
