#!/usr/bin/env python3
"""Bake one subsection's picture into assets/data/subart.js.

The panels have a picture each; a subsection may have its own, and falls back to
its panel's when it does not. So this writes into a *table* keyed by
"<panel>/<slug>" and leaves every other entry alone — adding the twentieth
subsection costs one run, not a new file.

    python3 tools/make-subart.py academics assets/img/sub/zebra.png
    python3 tools/make-subart.py academics/groton assets/img/sub/groton.png
    python3 tools/make-subart.py academics assets/img/sub/zebra.jpg --seal 2 --fade left,bottom
    python3 tools/make-subart.py academics/groton assets/img/sub/groton-schoolhouse.png --cols 300
    python3 tools/make-subart.py --list
    python3 tools/make-subart.py --drop academics/groton

A key is either a whole panel ("academics") or one of its subsections
("academics/groton"); the subsection's picture wins where there is one.

Storage is the portrait's contract: one hex digit of auto-levelled luminance per
cell, a space where the ground was keyed out, polarity decided at render time.

The ground is keyed by a flood *inward from the border*, never a threshold —
enclosed darks (a shield's chief, a window, an eye socket) are as dark as a dark
ground and a threshold erases them. Which direction to flood is read off the
border itself rather than configured, so a mark on white and a mark on black
both work. cells are averaged rather than sampled: a bake at 150 cells lands on
about 33, and a point sample at that ratio keeps or drops fine strokes at random.

A photograph cropped through its subject ends in a hard line where the frame
was. `--fade left,bottom[:0.16]` dissolves the picture into the ground toward
those edges instead, over that fraction of the width or height. The dissolve is
an ordered dither laid down in blocks the size of one of the field's cells, so it
survives the block-average onto the grid rather than collapsing back into a
line; luminance is left alone, since which end of it is ink is decided per theme
at render time.

`--cols N` bakes at N cells across instead of 150. A wide picture is fitted to
the window's width by the field, and at a small cell size that can be more cells
than the bake has, so a wide subject with fine detail wants a finer bake.

`--ink dark|light` fixes which end of the luminance is the ink, in both themes.
By default the ground decides: bright is ink on the dark ground and dark is ink
on paper, which is how a drawn mark is printed either way. A photograph of a
black object wants its dark parts dense whatever the ground, or on the dark
ground it renders as its own negative, a black piano as a faint outline with
bright keys: that is `--ink dark`.
"""
import json, re, sys
from collections import deque
from pathlib import Path
from PIL import Image

OUT    = Path('assets/data/subart.js')
COLS   = 150
MARGIN = 0.18     # ground must differ from the border median by at least this
SEAL   = 0        # px to close hairline gaps in an outline before flooding
LEVELS = 16
HEX    = '0123456789abcdef'
KEY_RE = re.compile(r'^[a-z0-9-]+(/[a-z0-9-]+)?$')


def load_table():
    if not OUT.exists():
        return {}
    m = re.search(r'window\.LCSubArt\s*=\s*(\{.*\});', OUT.read_text(), re.S)
    return json.loads(m.group(1)) if m else {}


def write_table(table):
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '/* Generated by tools/make-subart.py — do not edit by hand.\n'
        '   One entry per "<panel>/<slug>" subsection that has its own picture.\n'
        '   One hex digit of auto-levelled luminance per cell; a space is ground. */\n'
        'window.LCSubArt = %s;\n' % json.dumps(table, indent=0, sort_keys=True),
        encoding='utf-8')


BAYER = ((0, 8, 2, 10), (12, 4, 14, 6), (3, 11, 1, 9), (15, 7, 13, 5))
GRID_COLS = 33    # about what the field draws a bake onto; the dither is blocked to it


def fade_cells(cells, edges, depth):
    """Dissolve the cells toward the named frame edges: ground, on an ordered
    dither in blocks of about one field cell, thickening with distance."""
    rows, cols = len(cells), len(cells[0])
    blk = max(1, round(cols / GRID_COLS))
    for j in range(rows):
        for i in range(cols):
            if cells[j][i] is None:
                continue
            k = 1.0
            if 'left' in edges:   k = min(k, i / (cols * depth))
            if 'right' in edges:  k = min(k, (cols - 1 - i) / (cols * depth))
            if 'top' in edges:    k = min(k, j / (rows * depth))
            if 'bottom' in edges: k = min(k, (rows - 1 - j) / (rows * depth))
            if k >= 1:
                continue
            k = k * k * (3 - 2 * k)
            if k <= (BAYER[(j // blk) % 4][(i // blk) % 4] + 0.5) / 16:
                cells[j][i] = None
    return cells


def bake(src, seal=SEAL, fade=None, cols=COLS, ink=None):
    im = Image.open(src).convert('RGB')
    W, H = im.size
    px = im.load()
    lum = [[(0.2126 * px[x, y][0] + 0.7152 * px[x, y][1] + 0.0722 * px[x, y][2]) / 255
            for x in range(W)] for y in range(H)]

    # which way to flood: read the border rather than be told
    edge = ([lum[0][x] for x in range(W)] + [lum[H - 1][x] for x in range(W)] +
            [lum[y][0] for y in range(H)] + [lum[y][W - 1] for y in range(H)])
    edge.sort()
    mid = edge[len(edge) // 2]
    pale = mid >= 0.5
    cutoff = mid - MARGIN if pale else mid + MARGIN
    ground = (lambda v: v >= cutoff) if pale else (lambda v: v <= cutoff)

    # A hairline outline blurs to something the ground test walks straight
    # through, and the flood then pours into an enclosed area it should have
    # stopped outside: a logo's white face joins the white page. Thickening
    # the non-ground marks before flooding closes those gaps; the band is
    # handed back afterwards so nothing is actually eaten.
    solid = [[not ground(lum[y][x]) for x in range(W)] for y in range(H)]
    barrier = solid
    for _ in range(seal):
        nxt = [row[:] for row in barrier]
        for y in range(H):
            for x in range(W):
                if barrier[y][x]: continue
                if ((x and barrier[y][x-1]) or (x+1 < W and barrier[y][x+1]) or
                    (y and barrier[y-1][x]) or (y+1 < H and barrier[y+1][x])):
                    nxt[y][x] = True
        barrier = nxt
    passable = lambda x, y: not barrier[y][x]

    bg = [[False] * W for _ in range(H)]
    q = deque()
    def seed(x, y):
        if passable(x, y) and not bg[y][x]:
            bg[y][x] = True; q.append((x, y))
    for x in range(W):
        seed(x, 0); seed(x, H - 1)
    for y in range(H):
        seed(0, y); seed(W - 1, y)
    if not q:
        sys.exit('no ground found at the border \u2014 is the subject bleeding off the edge?')
    while q:
        x, y = q.popleft()
        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= nx < W and 0 <= ny < H and not bg[ny][nx] and passable(nx, ny):
                bg[ny][nx] = True; q.append((nx, ny))

    if seal:                       # give back the band the thickening claimed
        for y in range(H):
            for x in range(W):
                if bg[y][x] and solid[y][x]: bg[y][x] = False

    keep = [(x, y) for y in range(H) for x in range(W) if not bg[y][x]]
    if not keep:
        sys.exit('nothing survived the key')
    x0 = min(p[0] for p in keep); x1 = max(p[0] for p in keep)
    y0 = min(p[1] for p in keep); y1 = max(p[1] for p in keep)
    sw, sh = x1 - x0 + 1, y1 - y0 + 1

    rows = round(cols * (sh / sw))
    cells = []
    for j in range(rows):
        ya = y0 + j * sh // rows
        yb = max(ya + 1, y0 + (j + 1) * sh // rows)
        line = []
        for i in range(cols):
            xa = x0 + i * sw // cols
            xb = max(xa + 1, x0 + (i + 1) * sw // cols)
            tot = n = all_ = 0
            for y in range(ya, yb):
                for x in range(xa, xb):
                    all_ += 1
                    if not bg[y][x]:
                        tot += lum[y][x]; n += 1
            line.append(tot / n if n * 2 >= all_ else None)
        cells.append(line)

    if fade:
        cells = fade_cells(cells, fade[0], fade[1])
    vals = [v for line in cells for v in line if v is not None]
    lo, hi = min(vals), max(vals)
    span = max(1e-3, hi - lo)
    def digit(v):
        if v is None:
            return ' '
        return HEX[min(LEVELS - 1, round(((v - lo) / span) ** 0.85 * (LEVELS - 1)))]
    grid = [''.join(digit(v) for v in line) for line in cells]
    kept = 100.0 * len(keep) / (W * H)
    out = {'cols': cols, 'rows': rows, 'levels': LEVELS, 'grid': grid,
           'src': Path(src).as_posix()}
    if seal: out['seal'] = seal
    if cols != COLS: out['bakeCols'] = cols
    if fade: out['fade'] = '%s:%g' % (','.join(fade[0]), fade[1])
    if ink: out['ink'] = ink
    return out, kept


def main():
    args = sys.argv[1:]
    table = load_table()
    if not args or args[0] in ('-h', '--help'):
        sys.exit(__doc__)
    if args[0] == '--list':
        for k in sorted(table):
            e = table[k]
            print('%-34s %3dx%-3d  %s' % (k, e['cols'], e['rows'], e.get('src', '?')))
        return
    if args[0] == '--drop':
        if len(args) < 2 or args[1] not in table:
            sys.exit('nothing to drop at %r' % (args[1] if len(args) > 1 else ''))
        table.pop(args[1]); write_table(table)
        print('dropped %s (%d left)' % (args[1], len(table)))
        return
    seal, fade, cols, ink = SEAL, None, COLS, None
    if '--ink' in args:
        i = args.index('--ink')
        ink = args[i + 1]; del args[i:i + 2]
        if ink not in ('dark', 'light'):
            sys.exit('--ink wants dark or light, got %r' % ink)
    if '--cols' in args:
        i = args.index('--cols')
        cols = int(args[i + 1]); del args[i:i + 2]
    if '--seal' in args:
        i = args.index('--seal')
        seal = int(args[i + 1]); del args[i:i + 2]
    if '--fade' in args:
        i = args.index('--fade')
        spec, _, depth = args[i + 1].partition(':'); del args[i:i + 2]
        edges = [e for e in spec.split(',') if e]
        bad = [e for e in edges if e not in ('left', 'right', 'top', 'bottom')]
        if bad or not edges:
            sys.exit('--fade wants edges from left,right,top,bottom, got %r' % spec)
        fade = (edges, float(depth) if depth else 0.16)
    if len(args) < 2:
        sys.exit('need a key ("academics" or "academics/groton") and an image path')
    key, src = args[0], args[1]
    if not KEY_RE.match(key):
        sys.exit('key must look like "academics/groton", got %r' % key)
    entry, kept = bake(src, seal, fade, cols, ink)
    table[key] = entry
    write_table(table)
    print('%s  %s  %dx%d cells  subject kept %.0f%% of frame  (%d entries, %.1f KB)'
          % (OUT, key, entry['cols'], entry['rows'], kept, len(table),
             OUT.stat().st_size / 1024))


if __name__ == '__main__':
    main()
